import type { Metadata } from "next";
import { cookies } from "next/headers";
import "@/styles/globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { suite } from "@/styles/font";

export const metadata: Metadata = {
  title: "Heojoooon's blog",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const checkIsDarkMode = async () => {
    const nextCookies = cookies();

    if (nextCookies.get("theme")?.value === "dark") {
      return true;
    } else {
      return false;
    }
  };
  const isDark = await checkIsDarkMode();

  return (
    <html lang="ko" className={isDark ? "dark" : ""}>
      <body
        className={`${suite.className} bg-white dark:bg-slate-800 transition duration-200`}
      >
        <div className="flex flex-col gap-8">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
